new makefile, and fixed mem leak

diff --git a/push2/Makefile b/push2/Makefile
--- a/push2/Makefile
+++ b/push2/Makefile
@@ -5,92 +5,161 @@
 #                                                     +:+ +:+         +:+      #
 #    By: jfernand <jfernand@student.42porto.com>    +#+  +:+       +#+         #
 #                                                 +#+#+#+#+#+   +#+            #
-#    Created: 2025/04/02 19:45:19 by jfernand          #+#    #+#              #
-#    Updated: 2025/06/03 20:03:44 by jfernand         ###   ########.fr        #
+#    Created: 2025/06/13 19:06:00 by jfernand          #+#    #+#              #
+#    Updated: 2025/06/13 19:06:00 by jfernand         ###   ########.fr        #
 #                                                                              #
 # **************************************************************************** #
 
-# Name of the project
-NAME= push_swap
+################################################################################
+#                               Configuration                                 #
+################################################################################
 
-# Object files
-CFILES= \
-	srcs/func_push.c        \
-	srcs/func_rotate.c      \
-	srcs/func_rv_rotate.c   \
-	srcs/func_swap.c        \
-	srcs/main.c             \
-	srcs/parsing.c          \
-	srcs/push_swap.c        \
-	srcs/sort_big.c         \
-	srcs/sort_five_or_less.c\
-	srcs/sort_three.c       \
-	srcs/utils_list.c       \
-	srcs/utils_parsing.c    \
-	srcs/utils_more_list.c  \
-	srcs/utils_op_list.c    \
-	srcs/optimize_op.c      \
-	srcs/utils_sort_big.c
-
-# .h files
-HFILES= ./includes/push_swap.h \
-
-# Libft files
-LIBFT= ./libft
-LIBFT_A= $(LIBFT)/libft.a
-
-# .c bonus files
-#BFILES= 
-
-# Object files
-OFILES= $(CFILES:.c=.o)
-
-# Bonus object files
-#BOFILES= $(BFILES:.c=.o)
+# Output binary
+NAME     := push_swap
 
 # Compiler
-CC=@cc
+CC       := cc
+CFLAGS   := -Wall -Wextra -Werror -g
 
-# Flags for compiler
-CCFLAGS=-Wall      \
-        -Wextra    \
-        -Werror    \
-		-g         \
-		-I.        \
-		-I$(LIBFT) \
+# Directories
+INC_DIR := includes
+SRC_DIR := src
+OBJ_DIR := obj
 
-# Command used to clean target
-RM = rm -rf
+# Libft
+LIBFT_DIR := libft
+LIBFT_LIB := $(LIBFT_DIR)/libft.a
 
-#
-# Compilation and linking
-#
-all: $(NAME)
+# Source files
+SRC := \
+	$(SRC_DIR)/func_push.c        \
+	$(SRC_DIR)/func_rotate.c      \
+	$(SRC_DIR)/func_rv_rotate.c   \
+	$(SRC_DIR)/func_swap.c        \
+	$(SRC_DIR)/main.c             \
+	$(SRC_DIR)/parsing.c          \
+	$(SRC_DIR)/push_swap.c        \
+	$(SRC_DIR)/sort_big.c         \
+	$(SRC_DIR)/sort_five_or_less.c\
+	$(SRC_DIR)/sort_three.c       \
+	$(SRC_DIR)/utils_list.c       \
+	$(SRC_DIR)/utils_parsing.c    \
+	$(SRC_DIR)/utils_more_list.c  \
+	$(SRC_DIR)/utils_op_list.c    \
+	$(SRC_DIR)/optimize_op.c      \
+	$(SRC_DIR)/utils_sort_big.c
 
-$(NAME): $(LIBFT_A) $(OFILES) 
-	@ echo 'Building binary: $@'
-	$(CC) $(CCFLAGS) $(OFILES) $(LIBFT_A) -o $@
-	@ echo 'Finished building binary: $@'
+TOTAL := $(words $(SRC))
 
-$(OFILES): %.o:%.c
-	@ echo 'Building target: $@'
-	@ $(CC) $(CCFLAGS) -c $< -o $@
 
-$(LIBFT_A):
-	$(MAKE) -C $(LIBFT)
+# Object files
+OBJ      = $(SRC:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)
+DEP      = $(OBJ:.o=.d)
+RM       = rm -rf
+
+# Detect platform
+UNAME_S := $(shell uname -s)
+
+ifeq ($(UNAME_S),Linux)
+    PLATFORM := linux
+    CFLAGS += -DLINUX
+else ifeq ($(UNAME_S),Darwin)
+    PLATFORM := macos
+    CFLAGS += -DMACOS
+else ifneq (,$(findstring MINGW,$(UNAME_S)))
+    PLATFORM := windows
+    CFLAGS += -DWINDOWS
+else
+    PLATFORM := unknown
+endif
+
+################################################################################
+#                                Compilation                                   #
+################################################################################
+
+# Default target
+all: check deps $(NAME)
+	@echo "Building for platform: $(PLATFORM)"
+
+# Compile the program
+$(NAME): $(LIBFT_LIB) $(OBJ)
+	@echo "Linking $(NAME)..."
+	@$(CC) $(CFLAGS) $(OBJ) -I$(LIBFT_DIR) -L$(LIBFT_DIR) -lft -I$(INC_DIR) -o $(NAME)
+	@echo ""  # new line after progress bar
+
+$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
+	@mkdir -p $(dir $@)
+	@i=$(shell echo $(SRC) | tr ' ' '\n' | grep -n "^$<$$" | cut -d: -f1); \
+	bar_width=10; \
+	progress=$$((i * bar_width / $(TOTAL))); \
+	dots=$$(printf "%*s" $$progress | tr ' ' '#'); \
+	spaces=$$(printf "%*s" $$((bar_width - progress))); \
+	printf "\r[%s%s]  %d/%d Compiling %s\n" "$$dots" "$$spaces" $$i $(TOTAL) $<;
+	@$(CC) -MMD -MP $(CFLAGS) -I$(INC_DIR) -c $< -o $@ > /dev/null
+
+$(LIBFT_LIB):
+	$(MAKE) -C $(LIBFT_DIR)
+
+# Submodule initialization
+deps:
+	@git submodule update --init --recursive
+
+# Pull latest commits inside submodules
+pull:
+	@echo "Pulling latest submodule commits..."
+	@git submodule foreach git pull origin main
+
+# Update submodules to latest remote commits (tracked branch)
+update:
+	@echo "Updating submodules to latest remote commit..."
+	@git submodule update --remote --merge
+
+# Restore submodules to their committed state
+restore:
+	@read -p "⚠️ This will discard ALL submodule changes! Continue? (y/N) " ans; \
+	if [ "$$ans" = "y" ] || [ "$$ans" = "Y" ]; then \
+		echo "Restoring submodules..."; \
+		git submodule foreach --recursive git reset --hard; \
+		git submodule update --init --recursive; \
+	else \
+		echo "Restore canceled."; \
+	fi
+
+check:
+	@echo "Checking for uncommitted changes in submodules..."
+	@dirty=0; \
+	git submodule foreach --quiet ' \
+		status=$$(git status --porcelain); \
+		if [ -n "$$status" ]; then \
+			echo "Submodule $$path has uncommitted changes:"; \
+			echo "$$status"; \
+			exit 1; \
+		fi' || dirty=1; \
+	if [ $$dirty -eq 1 ]; then \
+		echo "Please commit or stash submodule changes before building."; \
+		exit 1; \
+	else \
+		echo "All submodules clean."; \
+	fi
+
+################################################################################
+#                                 Clean Up                                     #
+################################################################################
 
 clean:
-	@ $(RM) $(OFILES)
-	@ $(MAKE) -C $(LIBFT) clean
+	$(RM) $(OBJ_DIR)
+	$(MAKE) -C $(LIBFT_DIR) clean
 
 fclean: clean
-	@ $(RM) $(NAME)
-	@ $(MAKE) -C $(LIBFT) fclean
+	$(RM) $(NAME)
+	$(MAKE) -C $(LIBFT_DIR) fclean
 
 re: fclean all
 
-.PHONY= all clean fclean re 
+################################################################################
+#                                   Phony Targets                              #
+################################################################################
 
+.PHONY: all clean fclean re deps pull update restore check
 
-
-
+-include $(DEP)
